import { Metadata } from "next"

export const metadata:Metadata = {
  title: {
    default:"Next js tutorial",
    template:"%s | Sevinjily",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <header style={{backgroundColor:'green',padding:'1rem'}}>
        Welcome to Sevinj lessons
        </header>
        {children}
        <footer style={{backgroundColor:"pink",padding:'1rem'}}>
        All authority prevent from Sevinj
        </footer>
        </body>
    </html>
  )
}
